import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cart | Specter store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
