import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AppProvider } from "./provider/Providers";
import { Toaster } from "@/components/ui/toaster";
import {
  QueryClient,
  dehydrate,
  HydrationBoundary,
  QueryClientProvider,
} from "@tanstack/react-query";
import { getData } from "./server/getFeaturedProducts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Specter store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: ["FeaturedProducts"],
    queryFn: () => getData("/products"),
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />
            {children}
            {modal}
            <Toaster />
          </HydrationBoundary>
        </AppProvider>
      </body>
    </html>
  );
}
