import LoginForm from "@/components/LoginForm";
import Link from "next/link";
import { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "Login | Specter store",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className="px-8">
      <h1 className="text-center">
        <Link
          href={"/"}
          className="font-semibold text-xl inline-block  mx-auto mt-4"
        >
          Specter Store
        </Link>
      </h1>

      <LoginForm />
    </div>
  );
};
export default Login;
